Repository spoonmap/server, pull requests merged in 2023-04, with the labels that each got.

#33 로그인 기능 구현
  .gitignore
  build.gradle
  src/main/java/xyz/spoonmap/server/authentication/CustomUserDetail.java
  src/main/java/xyz/spoonmap/server/authentication/JwtGenerator.java
  src/main/java/xyz/spoonmap/server/authentication/dto/LoginRequest.java
  src/main/java/xyz/spoonmap/server/authentication/filter/JwtAuthenticateFilter.java
  src/main/java/xyz/spoonmap/server/authentication/filter/JwtVerifyFilter.java
  src/main/java/xyz/spoonmap/server/config/WebSecurityConfig.java
  src/main/java/xyz/spoonmap/server/exception/member/UnauthorizedException.java
  src/main/java/xyz/spoonmap/server/member/entity/Member.java
  src/main/java/xyz/spoonmap/server/member/repository/MemberRepository.java
  src/main/java/xyz/spoonmap/server/member/service/CustomUserDetailsService.java
  src/main/resources/application.yml
Labels: feature

#35 Spring Security, QueryDSL 오류 해결
  src/main/java/xyz/spoonmap/server/config/QueryDslConfig.java
  src/main/java/xyz/spoonmap/server/config/SecurityConfig.java
  src/main/java/xyz/spoonmap/server/member/service/MemberService.java
  src/main/java/xyz/spoonmap/server/member/service/v1/MemberServiceV1.java
  src/main/java/xyz/spoonmap/server/util/password/BcryptPasswordEncoder.java
  src/main/java/xyz/spoonmap/server/util/password/PasswordEncoder.java
  src/test/java/xyz/spoonmap/server/member/service/v1/MemberServiceV1Test.java
Labels: fix

#34 Post CRUD
  build.gradle
  src/main/java/xyz/spoonmap/server/category/repository/CategoryRepository.java
  src/main/java/xyz/spoonmap/server/config/AwsConfig.java
  src/main/java/xyz/spoonmap/server/exception/category/CategoryNotFoundException.java
  src/main/java/xyz/spoonmap/server/exception/photo/PhotoUploadException.java
  src/main/java/xyz/spoonmap/server/exception/post/PostNotFoundException.java
  src/main/java/xyz/spoonmap/server/member/repository/MemberRepository.java
  src/main/java/xyz/spoonmap/server/photo/adapter/S3Adapter.java
  src/main/java/xyz/spoonmap/server/photo/entity/Photo.java
  src/main/java/xyz/spoonmap/server/photo/repository/PhotoRepository.java
  src/main/java/xyz/spoonmap/server/post/controller/v1/PostControllerV1.java
  src/main/java/xyz/spoonmap/server/post/dto/request/PostRequestDto.java
  src/main/java/xyz/spoonmap/server/post/dto/response/PostResponseDto.java
  src/main/java/xyz/spoonmap/server/post/entity/Post.java
  src/main/java/xyz/spoonmap/server/post/entity/enums/MealTime.java
  src/main/java/xyz/spoonmap/server/post/repository/PostRepository.java
  src/main/java/xyz/spoonmap/server/post/service/PostService.java
  src/main/java/xyz/spoonmap/server/post/service/v1/PostServiceV1.java
  src/main/java/xyz/spoonmap/server/restaurant/dto/request/RestaurantRequestDto.java
  src/main/java/xyz/spoonmap/server/restaurant/dto/response/RestaurantResponseDto.java
  src/main/java/xyz/spoonmap/server/restaurant/entity/Restaurant.java
  src/main/java/xyz/spoonmap/server/restaurant/repository/RestaurantRepository.java
  src/test/java/xyz/spoonmap/server/post/controller/v1/PostControllerV1Test.java
  src/test/java/xyz/spoonmap/server/post/service/v1/PostServiceV1Test.java
Labels: feature

#36 Feature/member profile
  src/main/java/xyz/spoonmap/server/authentication/CustomUserDetail.java
  src/main/java/xyz/spoonmap/server/authentication/JwtGenerator.java
  src/main/java/xyz/spoonmap/server/authentication/filter/AuthenticateFilter.java
  src/main/java/xyz/spoonmap/server/authentication/filter/JwtVerifyFilter.java
  src/main/java/xyz/spoonmap/server/config/WebSecurityConfig.java
  src/main/java/xyz/spoonmap/server/member/controller/v1/MemberProfileControllerV1.java
  src/main/java/xyz/spoonmap/server/member/dto/request/PasswordUpdateRequest.java
  src/main/java/xyz/spoonmap/server/member/dto/response/MemberResponse.java
  src/main/java/xyz/spoonmap/server/member/entity/Member.java
  src/main/java/xyz/spoonmap/server/member/repository/MemberProfileRepository.java
  src/main/java/xyz/spoonmap/server/member/service/MemberProfileService.java
  src/main/java/xyz/spoonmap/server/member/service/v1/MemberProfileServiceV1.java
Labels: feature

#38 feat: Follow, Follower 조회 및 추가, 수락
  src/main/java/xyz/spoonmap/server/exception/relation/RelationNotFoundException.java
  src/main/java/xyz/spoonmap/server/relation/controller/v1/FollowControllerV1.java
  src/main/java/xyz/spoonmap/server/relation/controller/v1/FollowerControllerV1.java
  src/main/java/xyz/spoonmap/server/relation/dto/request/FollowRequest.java
  src/main/java/xyz/spoonmap/server/relation/dto/response/FollowAddResponse.java
  src/main/java/xyz/spoonmap/server/relation/dto/response/FollowResponse.java
  src/main/java/xyz/spoonmap/server/relation/dto/response/FollowerResponse.java
  src/main/java/xyz/spoonmap/server/relation/entity/Relation.java
  src/main/java/xyz/spoonmap/server/relation/repository/RelationRepository.java
  src/main/java/xyz/spoonmap/server/relation/repository/RelationRepositoryCustom.java
  src/main/java/xyz/spoonmap/server/relation/repository/RelationRepositoryImpl.java
  src/main/java/xyz/spoonmap/server/relation/service/RelationService.java
  src/main/java/xyz/spoonmap/server/relation/service/v1/RelationServiceV1.java
  src/test/java/xyz/spoonmap/server/ServerApplicationTests.java
  src/test/java/xyz/spoonmap/server/member/service/v1/MemberServiceV1Test.java
Labels: feature

#39 Fix/build
  .github/workflows/ci-cd.yml
  .gitignore
  build.gradle
  src/main/java/xyz/spoonmap/server/authentication/CustomUserDetail.java
  src/main/java/xyz/spoonmap/server/authentication/JwtGenerator.java
  src/main/java/xyz/spoonmap/server/config/WebSecurityConfig.java
  src/main/java/xyz/spoonmap/server/member/controller/v1/MemberProfileControllerV1.java
  src/main/resources/application.yml
  src/test/java/xyz/spoonmap/server/post/service/v1/PostServiceV1Test.java
Labels: feature

#47 feat: RestControllerAdvice를 활용한 오류 처리 #45
  src/main/generated/xyz/spoonmap/server/category/entity/QCategory.java
  src/main/generated/xyz/spoonmap/server/comment/entity/QComment.java
  src/main/generated/xyz/spoonmap/server/member/entity/QMember.java
  src/main/generated/xyz/spoonmap/server/notification/entity/QNotification.java
  src/main/generated/xyz/spoonmap/server/photo/entity/QPhoto.java
  src/main/generated/xyz/spoonmap/server/post/entity/QPost.java
  src/main/generated/xyz/spoonmap/server/relation/entity/QRelation.java
  src/main/generated/xyz/spoonmap/server/relation/entity/QRelation_Pk.java
  src/main/generated/xyz/spoonmap/server/restaurant/entity/QRestaurant.java
  src/main/generated/xyz/spoonmap/server/spoon/entity/QSpoon.java
  src/main/generated/xyz/spoonmap/server/spoon/entity/QSpoon_Pk.java
  src/main/java/xyz/spoonmap/server/authentication/JwtGenerator.java
  src/main/java/xyz/spoonmap/server/authentication/filter/AuthenticateFilter.java
  src/main/java/xyz/spoonmap/server/dto/response/ErrorResponse.java
  src/main/java/xyz/spoonmap/server/exception/category/CategoryNotFoundException.java
  src/main/java/xyz/spoonmap/server/exception/controlleradvice/AuthControllerAdvice.java
  src/main/java/xyz/spoonmap/server/exception/controlleradvice/GlobalControllerAdvice.java
  src/main/java/xyz/spoonmap/server/exception/controlleradvice/PhotoRestControllerAdvice.java
  src/main/java/xyz/spoonmap/server/exception/domain/category/CategoryNotFoundException.java
  src/main/java/xyz/spoonmap/server/exception/domain/common/NotFoundException.java
  src/main/java/xyz/spoonmap/server/exception/domain/member/MemberNotFoundException.java
  src/main/java/xyz/spoonmap/server/exception/domain/member/MemberWithdrawException.java
  src/main/java/xyz/spoonmap/server/exception/domain/member/UnauthorizedException.java
  src/main/java/xyz/spoonmap/server/exception/domain/photo/PhotoUploadException.java
  src/main/java/xyz/spoonmap/server/exception/domain/post/PostNotFoundException.java
  src/main/java/xyz/spoonmap/server/exception/domain/relation/RelationNotFoundException.java
  src/main/java/xyz/spoonmap/server/exception/member/MemberNotFoundException.java
  src/main/java/xyz/spoonmap/server/exception/post/PostNotFoundException.java
  src/main/java/xyz/spoonmap/server/exception/relation/RelationNotFoundException.java
  src/main/java/xyz/spoonmap/server/member/controller/v1/MemberProfileControllerV1.java
  src/main/java/xyz/spoonmap/server/member/service/CustomUserDetailsService.java
  src/main/java/xyz/spoonmap/server/member/service/v1/MemberProfileServiceV1.java
  src/main/java/xyz/spoonmap/server/member/service/v1/MemberServiceV1.java
  src/main/java/xyz/spoonmap/server/post/service/v1/PostServiceV1.java
  src/main/java/xyz/spoonmap/server/relation/service/v1/RelationServiceV1.java
  src/test/java/xyz/spoonmap/server/member/service/v1/MemberServiceV1Test.java
  src/test/java/xyz/spoonmap/server/post/service/v1/PostServiceV1Test.java
Labels: feature

#48 refactor: Post CRUD 리팩토링
  .github/workflows/ci-cd.yml
  src/main/java/xyz/spoonmap/server/member/dto/response/MemberResponse.java
  src/main/java/xyz/spoonmap/server/photo/adapter/S3Adapter.java
  src/main/java/xyz/spoonmap/server/photo/entity/Photo.java
  src/main/java/xyz/spoonmap/server/post/controller/v1/PostControllerV1.java
  src/main/java/xyz/spoonmap/server/post/dto/request/PostSaveRequestDto.java
  src/main/java/xyz/spoonmap/server/post/dto/request/PostUpdateRequestDto.java
  src/main/java/xyz/spoonmap/server/post/dto/response/PostResponseDto.java
  src/main/java/xyz/spoonmap/server/post/entity/Post.java
  src/main/java/xyz/spoonmap/server/post/service/PostService.java
  src/main/java/xyz/spoonmap/server/post/service/v1/PostServiceV1.java
  src/main/java/xyz/spoonmap/server/restaurant/dto/request/RestaurantRequestDto.java
  src/main/java/xyz/spoonmap/server/restaurant/dto/response/RestaurantResponseDto.java
  src/test/java/xyz/spoonmap/server/photo/entity/PhotoTest.java
  src/test/java/xyz/spoonmap/server/post/repository/PostRepositoryTest.java
Labels: refactor

#49 Feature/log
  src/main/java/xyz/spoonmap/server/aop/log/LogTraceAspect.java
  src/main/java/xyz/spoonmap/server/aop/log/LogTraceThreadLocal.java
  src/main/java/xyz/spoonmap/server/exception/controlleradvice/GlobalControllerAdvice.java
  src/main/java/xyz/spoonmap/server/member/controller/v1/MemberProfileControllerV1.java
  src/main/java/xyz/spoonmap/server/member/service/v1/MemberProfileServiceV1.java
Labels: feature

#50 Test/post
  src/main/java/xyz/spoonmap/server/post/controller/v1/PostControllerV1.java
  src/test/java/xyz/spoonmap/server/post/repository/PostRepositoryTest.java
  src/test/java/xyz/spoonmap/server/post/service/v1/PostServiceV1Test.java
Labels: chore

#51 feat: 댓글 기능
  src/main/java/xyz/spoonmap/server/comment/controller/v1/CommentControllerV1.java
  src/main/java/xyz/spoonmap/server/comment/dto/request/CommentSaveRequestDto.java
  src/main/java/xyz/spoonmap/server/comment/dto/request/CommentUpdateRequestDto.java
  src/main/java/xyz/spoonmap/server/comment/dto/response/CommentResponseDto.java
  src/main/java/xyz/spoonmap/server/comment/entity/Comment.java
  src/main/java/xyz/spoonmap/server/comment/repository/CommentRepository.java
  src/main/java/xyz/spoonmap/server/comment/service/CommentService.java
  src/main/java/xyz/spoonmap/server/comment/service/v1/CommentServiceV1.java
  src/main/java/xyz/spoonmap/server/exception/domain/comment/CommentNotFoundException.java
  src/test/java/xyz/spoonmap/server/comment/repository/CommentRepositoryTest.java
  src/test/java/xyz/spoonmap/server/comment/service/v1/CommentServiceV1Test.java
Labels: feature

#52 refactor: Post 기능 리팩토링
  src/main/java/xyz/spoonmap/server/post/controller/v1/PostControllerV1.java
  src/main/java/xyz/spoonmap/server/post/service/PostService.java
  src/main/java/xyz/spoonmap/server/post/service/v1/PostServiceV1.java
  src/test/java/xyz/spoonmap/server/post/service/v1/PostServiceV1Test.java
Labels: refactor

#56 test: post
  src/main/java/xyz/spoonmap/server/post/controller/v1/PostControllerV1.java
  src/main/java/xyz/spoonmap/server/post/dto/response/PostResponseDto.java
  src/main/java/xyz/spoonmap/server/post/service/PostService.java
  src/main/java/xyz/spoonmap/server/post/service/v1/PostServiceV1.java
  src/test/java/xyz/spoonmap/server/post/controller/v1/PostControllerV1Test.java
  src/test/resources/images/test.jpeg
Labels: chore

#55 test: comment controller
  src/main/java/xyz/spoonmap/server/comment/controller/v1/CommentControllerV1.java
  src/test/java/xyz/spoonmap/server/comment/controller/v1/CommentControllerV1Test.java
  src/test/java/xyz/spoonmap/server/comment/repository/CommentRepositoryTest.java
  src/test/java/xyz/spoonmap/server/post/controller/v1/PostControllerV1Test.java
  src/test/java/xyz/spoonmap/server/post/repository/PostRepositoryTest.java
Labels: chore

#57 프로필 이미지 변경 및 기타
  src/main/java/xyz/spoonmap/server/authentication/CustomUserDetail.java
  src/main/java/xyz/spoonmap/server/config/security/Path.java
  src/main/java/xyz/spoonmap/server/config/security/WebSecurityConfig.java
  src/main/java/xyz/spoonmap/server/dto/response/ErrorResponse.java
  src/main/java/xyz/spoonmap/server/dto/response/Response.java
  src/main/java/xyz/spoonmap/server/exception/controlleradvice/GlobalControllerAdvice.java
  src/main/java/xyz/spoonmap/server/exception/domain/member/DuplicateException.java
  src/main/java/xyz/spoonmap/server/member/controller/v1/MemberProfileControllerV1.java
  src/main/java/xyz/spoonmap/server/member/entity/Member.java
  src/main/java/xyz/spoonmap/server/member/enums/DuplicationType.java
  src/main/java/xyz/spoonmap/server/member/service/MemberProfileService.java
  src/main/java/xyz/spoonmap/server/member/service/v1/MemberProfileServiceV1.java
  src/main/java/xyz/spoonmap/server/photo/adapter/S3Adapter.java
  src/test/java/xyz/spoonmap/server/member/controller/v1/MemberProfileControllerV1Test.java
  src/test/java/xyz/spoonmap/server/member/service/v1/MemberProfileServiceV1Test.java
  src/test/java/xyz/spoonmap/server/util/AntMatcherTest.java
  src/test/java/xyz/spoonmap/server/util/MultipartBuilder.java
  src/test/java/xyz/spoonmap/server/util/RandomEntityGenerator.java
Labels: feature

#61 feat: Spoon 기능 개발
  src/main/java/xyz/spoonmap/server/exception/domain/spoon/SpoonNotFoundException.java
  src/main/java/xyz/spoonmap/server/post/controller/v1/PostControllerV1.java
  src/main/java/xyz/spoonmap/server/spoon/controller/SpoonControllerV1.java
  src/main/java/xyz/spoonmap/server/spoon/dto/SpoonDeleteResponseDto.java
  src/main/java/xyz/spoonmap/server/spoon/dto/SpoonResponseDto.java
  src/main/java/xyz/spoonmap/server/spoon/entity/Spoon.java
  src/main/java/xyz/spoonmap/server/spoon/repository/SpoonRepository.java
  src/main/java/xyz/spoonmap/server/spoon/service/SpoonService.java
  src/main/java/xyz/spoonmap/server/spoon/service/v1/SpoonServiceV1.java
  src/test/java/xyz/spoonmap/server/spoon/controller/SpoonControllerTest.java
  src/test/java/xyz/spoonmap/server/spoon/repository/SpoonRepositoryTest.java
  src/test/java/xyz/spoonmap/server/spoon/service/v1/SpoonServiceV1Test.java
Labels: feature

#63 알림
  src/main/java/xyz/spoonmap/server/ServerApplication.java
  src/main/java/xyz/spoonmap/server/authentication/filter/JwtVerifyFilter.java
  src/main/java/xyz/spoonmap/server/comment/dto/response/CommentResponseDto.java
  src/main/java/xyz/spoonmap/server/comment/repository/CommentRepository.java
  src/main/java/xyz/spoonmap/server/comment/service/CommentService.java
  src/main/java/xyz/spoonmap/server/comment/service/v1/CommentServiceV1.java
  src/main/java/xyz/spoonmap/server/exception/domain/notification/InvalidNotificationTypeException.java
  src/main/java/xyz/spoonmap/server/exception/domain/relation/FollowExistException.java
  src/main/java/xyz/spoonmap/server/notification/aop/NotificationAspect.java
  src/main/java/xyz/spoonmap/server/notification/controller/v1/NotificationControllerV1.java
  src/main/java/xyz/spoonmap/server/notification/dto/response/NotificationResponse.java
  src/main/java/xyz/spoonmap/server/notification/dto/response/SliceResponse.java
  src/main/java/xyz/spoonmap/server/notification/entity/Notification.java
  src/main/java/xyz/spoonmap/server/notification/entity/enums/NotificationType.java
  src/main/java/xyz/spoonmap/server/notification/event/NotificationEvent.java
  src/main/java/xyz/spoonmap/server/notification/event/eventlistener/NotificationEventListener.java
  src/main/java/xyz/spoonmap/server/notification/repository/NotificationRepository.java
  src/main/java/xyz/spoonmap/server/notification/repository/NotificationRepositoryCustom.java
  src/main/java/xyz/spoonmap/server/notification/repository/NotificationRepositoryImpl.java
  src/main/java/xyz/spoonmap/server/notification/service/NotificationService.java
  src/main/java/xyz/spoonmap/server/notification/service/v1/NotificationServiceV1.java
  src/main/java/xyz/spoonmap/server/relation/entity/Relation.java
  src/main/java/xyz/spoonmap/server/relation/service/v1/RelationServiceV1.java
  src/test/java/xyz/spoonmap/server/comment/service/v1/CommentServiceV1Test.java
  src/test/java/xyz/spoonmap/server/notification/aop/NotificationAspectTest.java
  src/test/java/xyz/spoonmap/server/notification/controller/v1/NotificationControllerV1Test.java
  src/test/java/xyz/spoonmap/server/notification/repository/NotificationRepositoryTest.java
  src/test/java/xyz/spoonmap/server/notification/service/v1/NotificationServiceV1Test.java
  src/test/java/xyz/spoonmap/server/relation/service/v1/RelationServiceV1Test.java
  src/test/java/xyz/spoonmap/server/util/RandomEntityGenerator.java
Labels: feature
