Repository spoonmap/server, pull requests merged in 2023-03, with the labels that each got.

#2 initial commit
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  HELP.md
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/xyz/spoonmap/server/ServerApplication.java
  src/main/resources/application.properties
  src/test/java/xyz/spoonmap/server/ServerApplicationTests.java
Labels: feature

#3 Update issue templates
  .github/ISSUE_TEMPLATE/feature.md
Labels: documentation

#7 Docs/pull request template
  .github/PULL_REQUEST_TEMPLATE.md
  build.gradle
  src/main/java/xyz/spoonmap/server/ServerApplication.java
Labels: documentation

#8 AWS RDS 연결
  build.gradle
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: feature

#9 Feature/cicd
  .github/ISSUE_TEMPLATE/feature.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ci-cd.yml
  Dockerfile
Labels: feature

#11 fix: IP 제거에 if 추가
  .github/workflows/ci-cd.yml
Labels: bug

#10 CD
  .github/ISSUE_TEMPLATE/feature.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ci-cd.yml
  .gitignore
  Dockerfile
  HELP.md
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/xyz/spoonmap/server/ServerApplication.java
  src/main/resources/application.yml
  src/test/java/xyz/spoonmap/server/ServerApplicationTests.java
Labels: feature

#12 fix: Dockerfile ARG 수정
  Dockerfile
Labels: bug

#13 Update ci-cd.yml
  .github/workflows/ci-cd.yml
Labels: bug

#18 Fix/cicd
  .github/workflows/ci-cd.yml
  Dockerfile
Labels: bug

#20 Feature/entity
  src/main/java/xyz/spoonmap/server/ServerApplication.java
  src/main/java/xyz/spoonmap/server/category/entity/Category.java
  src/main/java/xyz/spoonmap/server/comment/entity/Comment.java
  src/main/java/xyz/spoonmap/server/notification/entity/Notification.java
  src/main/java/xyz/spoonmap/server/notification/entity/enums/NotificationType.java
  src/main/java/xyz/spoonmap/server/post/entity/Post.java
  src/main/java/xyz/spoonmap/server/post/entity/enums/MealTime.java
  src/main/java/xyz/spoonmap/server/restaurant/entity/Restaurant.java
Labels: feature

#23 Feature/entity mapping
  src/main/java/xyz/spoonmap/server/category/entity/Category.java
  src/main/java/xyz/spoonmap/server/member/entity/Member.java
  src/main/java/xyz/spoonmap/server/photo/entity/Photo.java
  src/main/java/xyz/spoonmap/server/relation/entity/Relation.java
  src/main/java/xyz/spoonmap/server/relation/enums/RelationStatus.java
  src/main/java/xyz/spoonmap/server/spoon/entity/Spoon.java
Labels: feature

#22 refactor: Entity 제약 조건 추가
  src/main/java/xyz/spoonmap/server/category/entity/Category.java
  src/main/java/xyz/spoonmap/server/comment/entity/Comment.java
  src/main/java/xyz/spoonmap/server/notification/entity/Notification.java
  src/main/java/xyz/spoonmap/server/post/entity/Post.java
  src/main/java/xyz/spoonmap/server/restaurant/entity/Restaurant.java
Labels: refactor

#29 개발용 docker-compose 작성
  .gitignore
  docker-dev/docker-compose.yml
Labels: chore

#30 Feature/sign up
  build.gradle
  src/main/java/xyz/spoonmap/server/annotation/EmailValidation.java
  src/main/java/xyz/spoonmap/server/dto/response/Response.java
  src/main/java/xyz/spoonmap/server/exception/member/MemberNotFoundException.java
  src/main/java/xyz/spoonmap/server/member/aop/SignupMailAspect.java
  src/main/java/xyz/spoonmap/server/member/controller/v1/MemberControllerV1.java
  src/main/java/xyz/spoonmap/server/member/controller/v1/VerifyController.java
  src/main/java/xyz/spoonmap/server/member/dto/request/SignupRequest.java
  src/main/java/xyz/spoonmap/server/member/dto/response/SignupResponse.java
  src/main/java/xyz/spoonmap/server/member/entity/Member.java
  src/main/java/xyz/spoonmap/server/member/enums/Status.java
  src/main/java/xyz/spoonmap/server/member/repository/MemberRepository.java
  src/main/java/xyz/spoonmap/server/member/service/MemberService.java
  src/main/java/xyz/spoonmap/server/member/service/v1/MemberServiceV1.java
  src/main/java/xyz/spoonmap/server/post/entity/Post.java
  src/main/resources/application.yml
  src/main/resources/templates/signup.html
  src/test/java/xyz/spoonmap/server/member/controller/v1/MemberControllerV1Test.java
  src/test/java/xyz/spoonmap/server/member/controller/v1/VerifyControllerTest.java
  src/test/java/xyz/spoonmap/server/member/service/v1/MemberServiceV1Test.java
Labels: feature
